This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./LME-MPM.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file LME-MPM.acn....done (125 entries accepted, 0 rejected).
Sorting entries....done (913 comparisons).
Generating output file LME-MPM.acr....done (66 lines written, 0 warnings).
Output written in LME-MPM.acr.
Transcript written in LME-MPM.alg.
